openapi: 3.0.2
info:
  title: Montana Water Rights
  description: Montana Water Rights REST API
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1
paths:
  /applications/{applicationId}/water-rights/summary:
    get:
      summary: get the summary of water rights
      operationId: getWaterRightsSummary
      parameters:
        - in: path
          name: applicationId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: a summary of water rights
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationWaterRightsSummaryDto'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
    put:
      summary: edit the summary of water rights
      operationId: editWaterRightsSummary
      parameters:
        - in: path
          name: applicationId
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: The new Water Right summary
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationWaterRightsSummaryDto'
      responses:
        200:
          description: a summary of water rights
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationWaterRightsSummaryDto'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
  /applications/{applicationId}/water-rights:
    get:
      summary: get a page of water rights
      operationId: getWaterRights
      parameters: 
        - in: path
          name: applicationId
          required: true
          schema:
            type: integer
            format: int64
        - $ref: '#/components/parameters/pagenumber'
        - $ref: '#/components/parameters/pagesize'
        - $ref: '#/components/parameters/application-waterrights-sort-column'
        - $ref: '#/components/parameters/descsortdirection'
      responses:
        200:
          description: a list of Water Rights
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationWaterRightsPageDto'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
    post:
      summary: add a water right
      operationId: addWaterRight
      parameters:
        - in: path
          name: applicationId
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: The new Water Right
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationWaterRightCreationDto'
      responses:
        200:
          description: the new Water Right
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationWaterRightDto'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
  /applications/{applicationId}/water-rights/{waterRightId}/{version}:
    put:
      summary: edit a water right summary
      operationId: editWaterRight
      parameters:
        - in: path
          name: applicationId
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: waterRightId
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: version
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: The new Water Right
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationWaterRightDto'
      responses:
        200:
          description: the edited Water Right
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationWaterRightDto'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
    delete:
      summary: delete a Water Right
      operationId: deleteWaterRight
      parameters:
        - in: path
          name: applicationId
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: waterRightId
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: version
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: deleted the Water Right
        404:
          description: Either the Water Right Version or Application doesn't exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
components:
  schemas:
    ApplicationWaterRightsSummaryDto:
      type: object
      properties:
        maxFlowRate:
          type: number
          format: double
        flowRateUnit:
          type: string
          pattern: '^[ -~]+$'
        volume:
          type: number
          format: double
        acres:
          type: number
          format: double
        nonFiledWaterProject:
          type: boolean
        canPressNonFiledWaterProject:
          type: boolean
    ApplicationWaterRightsPageDto:
      type: object
      properties:
        pageSize:
          type: integer
        currentPage:
          type: integer
        totalPages:
          type: integer
        totalElements:
          type: integer
          format: int64
        filters:
          type: object
          additionalProperties:
            type: string
        sortDirection:
          $ref: '#/components/schemas/DescSortDirection'
        sortColumn:
          $ref: '#/components/schemas/ApplicationWaterRightSortColumn'
        results:
          type: array
          items:
            $ref: 'ApplicationWaterRightDto'
    ApplicationWaterRightCreationDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        version:
          type: integer
      required:
        - id
        - version
    ApplicationWaterRightDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        basin:
          type: string
        waterRightNumber:
          type: integer
          format: int64
        ext:
          type: string
        typeCode:
          type: string
        typeDescription:
          type: string
        version:
          type: integer
          format: int64
        versionTypeCode:
          type: string
        versionTypeDescription:
          type: string
        statusCode:
          type: string
          pattern: '^[ -~]+$'
        statusDescription:
          type: string
        versionStatusCode:
          type: string
          pattern: '^[ -~]+$'
        versionStatusDescription:
          type: string
        scanned:
          type: boolean
        scannedUrl:
          type: string
        numVersions:
          type: integer
        message:
          type: string
      required:
        - statusCode
        - versionStatusCode
    ApplicationWaterRightSortColumn:
      type: string
      enum: [BASIN, WATERRIGHTNUMBER, EXT, TYPEDESCRIPTION, VERSION, VERSIONTYPEDESCRIPTION, VERSIONSTATUSDESCRIPTION, STATUSDESCRIPTION]
      default: WATERRIGHTNUMBER
  parameters:
    application-waterrights-sort-column:
      name: sortColumn
      in: query
      description: The column to sort on
      schema:
        $ref: '#/components/schemas/ApplicationWaterRightSortColumn'