openapi: 3.0.2
info:
  title: Montana Water Rights
  description: "Montana Water Rights REST API"
  version: 0.0.1
servers:
- url: http://localhost:8080/api/v1
tags:
- name: Objectors
  description: Objectors
paths:
  /applications/{applicationId}/objections/{objectionId}/objectors:
    get:
      summary: get all the Objectors
      operationId: getObjectors
      parameters:
        - in: path
          name: applicationId
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: objectionId
          required: true
          schema:
            type: integer
            format: int64
        - $ref: '#/components/parameters/pagenumber'
        - $ref: '#/components/parameters/pagesize'
        - $ref: '#/components/parameters/objector-sort-column'
        - $ref: '#/components/parameters/descsortdirection'
      responses:
        200:
          description: a list of Objectors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectorsPageDto'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
  /applications/{applicationId}/objections/{objectionId}/objectors/{customerId}/representatives:
    get:
      summary: get a page of Representatives
      operationId: getObjectorRepresentatives
      parameters:
        - $ref: '#/components/parameters/pagenumber'
        - $ref: '#/components/parameters/pagesize'
        - $ref: '#/components/parameters/representative-sort-column'
        - $ref: '#/components/parameters/sortdirection'
        - in: path
          name: applicationId
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: objectionId
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: customerId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: a list of Representatives
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepresentativesPageDto'
components:
  schemas:
    ObjectorDto:
      type: object
      properties:
        contactId:
          type: integer
          format: int64
          x-message-name: Contact ID
        name:
          type: string
          pattern: '^[ -~]+$'
          maxLength: 75
        endDate:
          type: string
          format: date
          x-message-name: End Date
        representativeCount:
          type: integer
          format: int64
      example:
        contactId: 0
        endDate: 18/11/1985
    ObjectorsPageDto:
      type: object
      properties:
        pageSize:
          type: integer
        currentPage:
          type: integer
        totalPages:
          type: integer
        totalElements:
          type: integer
          format: int64
        filters:
          type: object
          additionalProperties:
            type: string
        sortDirection:
          $ref: '#/components/schemas/DescSortDirection'
        sortColumn:
          $ref: '#/components/schemas/ObjectorSortColumn'
        results:
           type: array
           items:
             $ref: '#/components/schemas/ObjectorDto'
    ObjectorSortColumn:
      type: string
      enum: [CONTACTID, NAME, ENDDATE]
      default: CONTACTID
  parameters:
    objector-sort-column:
      name: sortColumn
      in: query
      description: The column to sort on
      schema:
        $ref: '#/components/schemas/ObjectorSortColumn'