openapi: 3.0.2
info:
  title: Montana Water Rights
  description: Montana Water Rights REST API
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1
paths:
  /offices/regional:
    get:
      summary: get all the Regional Offices
      operationId: getAllRegionalOffices
      responses:
        200:
          description: all the available offices
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllOfficesDto'