openapi: 3.0.2
info:
  title: Montana Water Rights
  description: Montana Water Rights REST API
  version: 0.0.1
servers:
- url: http://localhost:8080/api/v1
paths:
  /sources:
    get:
      summary: retrieve a page of water right version PODs
      operationId: searchSources
      parameters:
        - $ref: '#/components/parameters/pagenumber'
        - $ref: '#/components/parameters/pagesize'
        - $ref: '#/components/parameters/sortdirection'
        - in: query
          name: sourceName
          schema:
            type: string
          description: The Name of the Source
      responses:
        200:
          description: a page of PODs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SourcePageDto'
    post:
      summary: create a new Source
      operationId: createSource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SourceCreationDto'
      responses:
        201:
          description: newly created source
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SourceDto'
components:
  schemas:
    SourcePageDto:
      type: object
      properties:
        pageSize:
          type: integer
        currentPage:
          type: integer
        totalPages:
          type: integer
        totalElements:
          type: integer
          format: int64
        filters:
          type: object
          additionalProperties:
            type: string
        sortDirection:
          $ref: '#/components/schemas/SortDirection'
        results:
          type: array
          items:
            $ref: '#/components/schemas/SourceDto'
    SourceDto:
      type: object
      properties:
        sourceId:
          type: integer
          format: int64
        sourceName:
          type: string
    SourceCreationDto:
      type: object
      properties:
        sourceName:
          type: string
        forkName:
          type: string
        knownAs:
          type: string
      required:
        - sourceName