openapi: 3.0.2
info:
  title: Montana Water Rights
  description: Montana Water Rights REST API
  version: 0.0.1
servers:
- url: http://localhost:8080/api/v1
paths:
  /water-rights/{waterRightId}/versions/{versionNumber}/remarks:
    get:
      summary: retrieve a page of water right version remarks
      operationId: getVersionRemarks
      parameters:
        - $ref: '#/components/parameters/water-right-id'
        - $ref: '#/components/parameters/version-number'
        - $ref: '#/components/parameters/pagenumber'
        - $ref: '#/components/parameters/pagesize'
        - $ref: '#/components/parameters/version-remarks-sort-column'
        - $ref: '#/components/parameters/sortdirection'
      responses:
        200:
          description: a page of relationships
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionRemarksPageDto'
    post:
      summary: create water right version remark
      operationId: createVersionRemark
      parameters:
        - $ref: '#/components/parameters/water-right-id'
        - $ref: '#/components/parameters/version-number'
      requestBody:
        description: water right version remark to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VersionRemarkCreateDto'
      responses:
        201:
          description: the new water right version remark
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemarkDto'
components:
  schemas:
    VersionRemarksPageDto:
      type: object
      properties:
        pageSize:
          type: integer
        currentPage:
          type: integer
        totalPages:
          type: integer
        totalElements:
          type: integer
          format: int64
        filters:
          type: object
          additionalProperties:
            type: string
        sortDirection:
          $ref: '#/components/schemas/SortDirection'
        sortColumn:
          $ref: '#/components/schemas/VersionRemarksSortColumn'
        results:
          type: array
          items:
            $ref: 'RemarkDto'
    RemarkDto:
      type: object
      properties:
        remarkId:
          type: integer
          format: int64
        remarkCode:
          type: string
        addedDate:
          type: string
          format: date
        remarkCategoryDescription:
          type: string
        remarkTypeDescription:
          type: string
        remarkStatusDescription:
          type: string
    VersionRemarkCreateDto:
      type: object
      properties:
        remarkCode:
          type: string
        addedDate:
          type: string
          format: date
      required:
        - remarkCode
        - addedDate
    VersionRemarksSortColumn:
      type: string
      enum: [ REMARKCODE, ADDEDDATE, REMARKCATEGORYDESCRIPTION, REMARKTYPEDESCRIPTION, REMARKSTATUSDESCRIPTION ]
      default: REMARKCODE
  parameters:
    version-remarks-sort-column:
      name: sortColumn
      in: query
      description: The column to sort on
      schema:
        $ref: '#/components/schemas/VersionRemarksSortColumn'