openapi: 3.0.2
info:
  title: Montana Water Rights
  description: Montana Water Rights REST API
  version: 0.0.1
servers:
- url: http://localhost:8080/api/v1
paths:
  /water-right-types/{typeCode}/water-right-statuses/all:
    get:
      summary: a list of all Water Right Statuses
      operationId: getAllWaterRightStatuses
      parameters:
        - in: path
          name: typeCode
          required: true
          schema:
            type: string
      responses:
        200:
          description: a list of Water Right Statuses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllWaterRightStatusesDto'
components:
  schemas:
    AllWaterRightStatusesDto:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/WaterRightStatusDto'
    WaterRightStatusDto:
      type: object
      properties:
        value:
          type: string
        description:
          type: string